<?php

/**
 * Copyright © Michał Biarda. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \MB\Inpost\ViewModel\ShipmentPackagingScript $viewModel */
$viewModel = $block->getData('view_model');
?>
<?php if ($viewModel->isInpostShipment()): ?>
<script type="text/x-magento-init">
{
    "*": {
        "MB_Inpost/js/shipment-packaging": <?= $viewModel->getJsConfig() ?>
    }
}
</script>
<?php endif; ?>
