<?php
/**
 * Copyright © Michał Biarda. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \MB\Inpost\ViewModel\Map $viewModel */
$viewModel = $block->getData('view_model');
?>
<script type="text/javascript">
    window.easyPackAsyncInit = function () {
        easyPack.init(<?= $viewModel->getJsConfig() ?>);
        easyPack.mapWidget('locker-map-wrapper', function(point) {
            window.parent.postMessage(
                {"mb_inpost_locker": point},
                "<?= $escaper->escapeUrl($block->getBaseUrl()) ?>"
            );
        });
    };
</script>
<div id="locker-map-wrapper">
    <span class="loading"></span>
</div>