<?php
/**
 * Copyright © Michał Biarda. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var $block Magento\Framework\View\Element\Template */
?>
<script type="text/javascript">
    window.easyPackAsyncInit = function () {
        easyPack.init({
            mapType: 'osm',
            searchType: 'osm',
        });
        easyPack.mapWidget('locker-map-wrapper', function(point) {
            window.parent.postMessage(
                {"mb_inpost_locker": point},
                "<?= /* @noEscape */ $block->getBaseUrl() ?>"
            );
        });
    };
</script>
<div id="locker-map-wrapper"></div>